// animations.ts

import { AnimationConfig, AnimationState } from "./types";

// 1. Centralized config: include cols & rows per animation state
export const animations: Record<AnimationState, AnimationConfig> = {
  welcome1: {
    src: require("../assets/character/welcome1.webp"),
    frames: 35,
    fps: 30,
    loop: false,
    width: 640,
    height: 432,
    cols: 6,
    rows: 6,
  },
  welcome2: {
    src: require("../assets/character/welcome2.webp"),
    frames: 40,
    fps: 30,
    loop: false,
    width: 640,
    height: 432,
    cols: 6,
    rows: 7,
  },
  welcome3: {
    src: require("../assets/character/welcome3.webp"),
    frames: 62,
    fps: 30,
    loop: false,
    width: 640,
    height: 432,
    cols: 6,
    rows: 11,
  },
  laughing: {
    src: require("../assets/character/laughing.webp"),
    frames: 53,
    fps: 30,
    loop: false,
    width: 608,
    height: 410,
    cols: 8,
    rows: 7,
  },
  hit: {
    src: require("../assets/character/hit.webp"),
    frames: 35,
    fps: 30,
    loop: false,
    width: 640,
    height: 432,
    cols: 6,
    rows: 6,
  },
  attack: {
    src: require("../assets/character/attack.webp"),
    frames: 99,
    fps: 30,
    loop: false,
    width: 640,
    height: 432,
    cols: 10,
    rows: 10,
  },
  victory: {
    src: require("../assets/character/victory.webp"),
    frames: 86,
    fps: 30,
    loop: false,
    width: 640,
    height: 272,
    cols: 10,
    rows: 9,
  },
};
